@startuml

!theme vibrant

interface World <<interface>> {
  -am: ArchetypeManager
  context: MetaContext
  mutator: Mutator
  entity(): EntityBuilder 
  update(e: Entity, c: Component)
  hasComponents(e: Entity, types: List[ComponentType]): Bool
  system(name: String, priority: Int, q: Query)
  system(s: System)
  loop(loopType: Loop)
}

interface Loop <<interface>>

interface MetaContext <<interface>> {
  deltaTime: DeltaSeconds
}

interface Mutator <<interface>> {
  defer(r: EntityRequest)
  process(r: SystemRequest)
}

interface EntityRequest <<interface>>
interface SystemRequest <<interface>>

interface ArchetypeManager <<interface>>

interface System <<interface>>

interface EntityBuilder <<interface>> {
  withComponents(c: Set[Component])
}

interface Query <<interface>>

World "1" *-- "1" MetaContext
World "1" *-- "1" Mutator
World "1" *-- "1" ArchetypeManager
World -> Loop
EntityBuilder <- World
Mutator --> EntityRequest
Mutator --> SystemRequest 
System "*" --o "1" World
Query -- World

hide interface circle
hide empty members

@enduml