# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: CI

on:
  push:
    tags:
      - "*.*.*"

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        scala-version: [3.5.0-RC4]

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'sbt'
    - name: Run tests
      run: sbt test
    - name: Build JARs
      run: sbt assembly
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          core/target/scala-${{ matrix.scala-version }}/ecscalibur.jar
          demo/ecs/target/scala-${{ matrix.scala-version }}/demo_ecs.jar
          demo/oop/target/scala-${{ matrix.scala-version }}/demo_oop.jar
      # Optional: This step uploads information to the GitHub dependency graph and unblocking Dependabot alerts for the repository
    - name: Upload dependency graph
      uses: scalacenter/sbt-dependency-submission@ab086b50c947c9774b70f39fc7f6e20ca2706c91
