name: Coverage

on:
  push:
    branches: [ coverage ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        scala: [3.5.2]

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'sbt'
    - name: Generate coverage reports
      run: sbt clean test coverageAggregate
    - name: Upload results to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        directory: target/scala-${{ matrix.scala }}/coverage-report/
