name: Coverage

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        scala: [3.5.0-RC4]

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'sbt'
    - name: Generate coverage reports
      run: |
        sbt 'core / clean ; coverage ; test ; coverageReport'
        sbt 'ecsutil / clean ; coverage ; test ; coverageReport'
    - name: Upload 'core' results to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        directory: core/target/scala-${{ matrix.scala }}/coverage-report/
    - name: Upload 'ecsutil' results to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        directory: ecsutil/target/scala-${{ matrix.scala }}/coverage-report/
