name: Coverage

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        scala: [3.5.0-RC4]

    steps:
      - name: Git checkout (merge)
        uses: actions/checkout@v3
        if: github.event_name != 'pull_request'
        with:
          fetch-depth: 0
      - name: Git checkout (PR)
        uses: actions/checkout@v3
        if: github.event_name == 'pull_request'
        with:
          fetch-depth: 0
          # see: https://frontside.com/blog/2020-05-26-github-actions-pull_request/#how-does-pull_request-affect-actionscheckout
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'sbt'
      - name: Run tests
        run: sbt 'core / clean ; coverage ; test'
      - name: Move cobertura.xml
        run: |
          mkdir -p target/scala-${{ matrix.scala }}/coverage-report/
          mv 'core/target/scala-${{ matrix.scala }}/coverage-report/cobertura.xml' 'target/scala-${{ matrix.scala }}/coverage-report/'
      - name: Upload coverage data to Coveralls
        run: sbt 'core / coverageReport ; coveralls'
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
          COVERALLS_FLAG_NAME: Scala ${{ matrix.scala }}
